"""removed original filename column

Revision ID: 4b689ddbfa55
Revises: 994821ea8bc2
Create Date: 2025-12-09 11:02:04.744609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b689ddbfa55'
down_revision: Union[str, Sequence[str], None] = '994821ea8bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
