"""Chunk model added

Revision ID: fa379c2825f2
Revises: cf72c680d3a6
Create Date: 2025-12-11 09:57:16.859886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa379c2825f2'
down_revision: Union[str, Sequence[str], None] = 'cf72c680d3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    
    # Rename enum from 'status' to 'file_status' and column from 'status' to 'file_status'
    # Step 1: Create the new enum type
    op.execute("CREATE TYPE file_status AS ENUM ('UPLOADED', 'PROCESSING', 'READY', 'FAILED')")
    
    # Step 2: Alter the column to use the new enum type
    op.execute("ALTER TABLE documents ALTER COLUMN status TYPE file_status USING status::text::file_status")
    
    # Step 3: Rename the column from 'status' to 'file_status'
    op.execute("ALTER TABLE documents RENAME COLUMN status TO file_status")
    
    # Step 4: Drop the old enum type
    op.execute("DROP TYPE status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename enum back from 'file_status' to 'status' and column back from 'file_status' to 'status'
    # Step 1: Rename the column back from 'file_status' to 'status'
    op.execute("ALTER TABLE documents RENAME COLUMN file_status TO status")
    
    # Step 2: Create the old enum type
    op.execute("CREATE TYPE status AS ENUM ('UPLOADED', 'PROCESSING', 'READY', 'FAILED')")
    
    # Step 3: Alter the column to use the old enum type
    op.execute("ALTER TABLE documents ALTER COLUMN status TYPE status USING status::text::status")
    
    # Step 4: Drop the new enum type
    op.execute("DROP TYPE file_status")
    
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
